### ISSUE TITLE
Ignored is not a great default.

### ISSUE THREAD

**Issue by SrGeneroso** [probablykasper/svelte-droplet#3]
Hi, I'm giving a twirl and learning about droppable components. Great comments for a noob, thanks for that.
My issue is that I think the default behavior of ignoring unnaccepted mimes or max files without error or callback is not great. I'm going to try to edit the component myself to see if I'm able to show some messages to the user. Please consider adding that feature.

**Comment by probablykasper** [comment]
I think I'll keep the behavior of ignoring unaccepted mimes/files. If you want to handle it yourself, it's always possible to check that inside your `handleFiles` function instead of setting the `allowsMimes` and `max` props.

Feel free to publish your own package if you find a solution you like!
